[package]
name = "trait-enumizer"
version = "0.1.0"
edition = "2021"

[dependencies]
trait-enumizer-derive = {path = "../trait-enumizer-derive"}
flume = {version="0.10.11", optional=true}
crossbeam-channel = {version="0.5.2", optional=true}

[dev-dependencies]
catty = "0.1.4"
crossbeam-channel = "0.5.2"
flume = "0.10.11"
futures = "0.3.21"
tokio = "1.17.0"

[features]
default=[]
returnval=[]
